apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: openshift-default
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gw-options
  addresses:
  - type: IPAddress
    value: {{ .Values.anycastIP }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
  namespace: default
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            readinessProbe:
              httpGet:
                path: /hello
                port: 80
                # httpHeaders:
                # - name: Host
                #   # This is the same hostname from HTTPRoute. In case this route is unavailable the livenessProbe will fail
                #   value: apps.anycast.goguybrush.com
              initialDelaySeconds: 3
              periodSeconds: 3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-hello-world-route
  namespace: east
spec:
  parentRefs:
  - name: example-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /frontend
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplaceFullPath
            replaceFullPath: /
    backendRefs:
    - name: frontend
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world-route
  namespace: hello-world
spec:
  parentRefs:
  - name: example-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /hello
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplaceFullPath
            replaceFullPath: /
    backendRefs:
    - name: hello-world
      port: 8080
